import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#06151a",
        "surface": "#06151a",
        "surface-dim": "#06151a",
        "surface-bright": "#2c3c41",
        "surface-container-lowest": "#021015",
        "surface-container-low": "#0e1e23",
        "surface-container": "#122227",
        "surface-container-high": "#1d2c32",
        "surface-container-highest": "#28373d",
        "surface-variant": "#28373d",
        "on-surface": "#d4e5ec",
        "on-surface-variant": "#bbcac6",
        "on-background": "#d4e5ec",
        "primary": "#fcfffd",
        "primary-container": "#6ff7e8",
        "on-primary": "#003732",
        "on-primary-container": "#007068",
        "primary-fixed": "#70f8e9",
        "primary-fixed-dim": "#4edbcd",
        "secondary": "#80d1f7",
        "secondary-container": "#007193",
        "on-secondary": "#003547",
        "on-secondary-container": "#cdedff",
        "secondary-fixed": "#bfe8ff",
        "secondary-fixed-dim": "#80d1f7",
        "tertiary": "#fffeff",
        "tertiary-container": "#ffe075",
        "tertiary-fixed": "#ffe179",
        "tertiary-fixed-dim": "#e2c55d",
        "on-tertiary": "#3b2f00",
        "on-tertiary-container": "#786200",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#859491",
        "outline-variant": "#3c4947",
        "inverse-surface": "#d4e5ec",
        "inverse-on-surface": "#233338",
        "inverse-primary": "#006a62",
        "surface-tint": "#4edbcd",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#00504a",
        "on-secondary-fixed": "#001f2a",
        "on-secondary-fixed-variant": "#004d65",
        "on-tertiary-fixed": "#231b00",
        "on-tertiary-fixed-variant": "#554500",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "Poppins", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
